import type { Metadata } from 'next';

import type { PropsWithChildren } from 'react';

import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from 'sonner';

import { cn } from '@/utils/tailwind-utils';

import '@/styles/globals.css';

import QueryProvider from '@/providers/query-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={cn('antialiased')} suppressHydrationWarning={true}>
        <NuqsAdapter>
          <QueryProvider>{children}</QueryProvider>
        </NuqsAdapter>
        <Toaster richColors closeButton duration={4000} />
      </body>
    </html>
  );
};

export default RootLayout;
